# Generated by Django 3.2.3 on 2021-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210428_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
